# Generated by Django 5.1.4 on 2024-12-25 15:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ProductsApp", "0002_initial"),
        ("UserApp", "0002_alter_modeluser_iscustomer"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Order Date",
                        verbose_name="Order Date",
                    ),
                ),
                (
                    "unique_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Order ID",
                        unique=True,
                        verbose_name="Order ID",
                    ),
                ),
                (
                    "address",
                    models.ForeignKey(
                        help_text="Address",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="UserApp.modeladdress",
                        verbose_name="Address",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
                "db_table": "Orders",
            },
        ),
        migrations.CreateModel(
            name="ModelOrderItems",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.PositiveIntegerField(
                        help_text="Quantity", verbose_name="Quantity"
                    ),
                ),
                (
                    "price",
                    models.PositiveIntegerField(
                        help_text="Price", verbose_name="Price"
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        help_text="Product",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ProductsApp.modelproduct",
                        verbose_name="Product",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        help_text="Order",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="OrderApp.modelorder",
                        verbose_name="Order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order Item",
                "verbose_name_plural": "Order Items",
                "db_table": "OrderItems",
            },
        ),
    ]
