# Generated by Django 5.1.4 on 2024-12-10 13:07

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unique_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Address ID",
                        unique=True,
                        verbose_name="Address ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Address Title",
                        max_length=50,
                        verbose_name="Address Title",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        choices=[
                            ("1", "ADANA"),
                            ("2", "ADIYAMAN"),
                            ("3", "AFYONKARAHÄ°SAR"),
                            ("4", "AÄžRI"),
                            ("5", "AMASYA"),
                            ("6", "ANKARA"),
                            ("7", "ANTALYA"),
                            ("8", "ARTVÄ°N"),
                            ("9", "AYDIN"),
                            ("10", "BALIKESÄ°R"),
                            ("11", "BÄ°LECÄ°KK"),
                            ("12", "BÄ°NGÃ–L"),
                            ("13", "BÄ°TLÄ°S"),
                            ("14", "BOLU"),
                            ("15", "BURDUR"),
                            ("16", "BURSA"),
                            ("17", "Ã‡ANAKKALE"),
                            ("18", "Ã‡ANKIRI"),
                            ("19", "Ã‡ORUM"),
                            ("20", "DENÄ°ZLÄ°"),
                            ("21", "DÄ°YARBAKIR"),
                            ("22", "EDÄ°RNE"),
                            ("23", "ELAZIÄž"),
                            ("24", "ERZÄ°NCAN"),
                            ("25", "ERZURUM"),
                            ("26", "ESKÄ°ÅžEHÄ°R"),
                            ("27", "GAZÄ°ANTEP"),
                            ("28", "GÄ°RESUN"),
                            ("29", "GÃœMÃœÅžHANE"),
                            ("30", "HAKKARÄ°"),
                            ("31", "HATAY"),
                            ("32", "ISPARTA"),
                            ("33", "MERSÄ°N"),
                            ("34", "Ä°STANBUL"),
                            ("35", "Ä°ZMÄ°R"),
                            ("36", "KARS"),
                            ("37", "KASTAMONU"),
                            ("38", "KAYSERÄ°"),
                            ("39", "KIRKLARELÄ°"),
                            ("40", "KIRÅžEHÄ°R"),
                            ("41", "KOCAELÄ°"),
                            ("42", "KONYA"),
                            ("43", "KÃœTAHYA"),
                            ("44", "MALATYA"),
                            ("45", "MANÄ°SA"),
                            ("46", "KAHRAMANMARAÅž"),
                            ("47", "MARDÄ°N"),
                            ("48", "MUÄžLA"),
                            ("49", "MUÅž"),
                            ("50", "NEVÅžEHÄ°R"),
                            ("51", "NÄ°ÄžDE"),
                            ("52", "ORDU"),
                            ("53", "RÄ°ZE"),
                            ("54", "SAKARYA"),
                            ("55", "SAMSUN"),
                            ("56", "SÄ°Ä°RT"),
                            ("57", "SÄ°NOP"),
                            ("58", "SÄ°VAS"),
                            ("59", "TEKÄ°RDAÄž"),
                            ("60", "TOKAT"),
                            ("61", "TRABZON"),
                            ("62", "TUNCELÄ°"),
                            ("63", "ÅžANLIURFA"),
                            ("64", "UÅžAK"),
                            ("65", "VAN"),
                            ("66", "YOZGAT"),
                            ("67", "ZONGULDAK"),
                            ("68", "AKSARAY"),
                            ("69", "BAYBURT"),
                            ("70", "KARAMAN"),
                            ("71", "KIRIKKALE"),
                            ("72", "BATMAN"),
                            ("73", "ÅžIRNAK"),
                            ("74", "BARTIN"),
                            ("75", "ARDAHAN"),
                            ("76", "IÄžDIR"),
                            ("77", "YALOVA"),
                            ("78", "KARABÃ¼K"),
                            ("79", "KÄ°LÄ°S"),
                            ("80", "OSMANÄ°YE"),
                            ("81", "DÃœZCE"),
                        ],
                        help_text="City",
                        max_length=20,
                        verbose_name="City",
                    ),
                ),
                (
                    "street",
                    models.CharField(
                        help_text="Street", max_length=150, verbose_name="Street"
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        help_text="Full Address",
                        max_length=500,
                        verbose_name="Full Address",
                    ),
                ),
            ],
            options={
                "verbose_name": "Address",
                "verbose_name_plural": "Addresses",
                "db_table": "Addresses",
            },
        ),
        migrations.CreateModel(
            name="ModelUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        help_text="Profile Picture",
                        null=True,
                        upload_to="Users",
                        verbose_name="Profile Picture",
                    ),
                ),
                (
                    "isCustomer",
                    models.BooleanField(
                        default=True,
                        help_text="Is the user a customer?",
                        verbose_name="Is Customer",
                    ),
                ),
                (
                    "address",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Addresses",
                        related_name="addrs",
                        to="UserApp.modeladdress",
                        verbose_name="Addresses",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="User Groups",
                        related_name="custom_user_set",
                        to="auth.group",
                        verbose_name="Groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="User Permissions",
                        related_name="custom_user_permissions",
                        to="auth.permission",
                        verbose_name="Permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "db_table": "Users",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
