# Generated by Django 5.1.4 on 2024-12-10 13:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("UserApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modeluser",
            name="isCustomer",
            field=models.BooleanField(
                default=False,
                help_text="Is the user a customer?",
                verbose_name="Is Customer",
            ),
        ),
    ]
