# Generated by Django 5.1.4 on 2024-12-10 13:07

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ModelProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        help_text="Slug",
                        populate_from="name",
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Description",
                        max_length=500,
                        verbose_name="Description",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Image",
                        null=True,
                        upload_to="Products",
                        verbose_name="Image",
                    ),
                ),
                (
                    "draft",
                    models.BooleanField(
                        default=True, help_text="Draft", verbose_name="Draft"
                    ),
                ),
                ("price", models.FloatField(help_text="Price", verbose_name="Price")),
                (
                    "shipping",
                    models.BooleanField(
                        default=True, help_text="Shipping", verbose_name="Shipping"
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "db_table": "Products",
            },
        ),
        migrations.CreateModel(
            name="ModelProductCategory",
            fields=[
                ("name", models.CharField(max_length=200)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        help_text="Slug",
                        populate_from="name",
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Category",
                "verbose_name_plural": "Product Categories",
                "db_table": "ProductCategories",
            },
        ),
    ]
