# Generated by Django 5.1.4 on 2024-12-10 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ProductsApp", "0001_initial"),
        ("SellerApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelproduct",
            name="seller",
            field=models.ForeignKey(
                help_text="Store",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="SellerApp.modelseller",
                verbose_name="Store",
            ),
        ),
        migrations.AddField(
            model_name="modelproduct",
            name="category",
            field=models.ManyToManyField(
                help_text="Category",
                related_name="categs",
                to="ProductsApp.modelproductcategory",
                verbose_name="Category",
            ),
        ),
    ]
