# Generated by Django 5.1.4 on 2024-12-10 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("SellerApp", "0001_initial"),
        ("UserApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelseller",
            name="user",
            field=models.ForeignKey(
                help_text="User",
                on_delete=django.db.models.deletion.CASCADE,
                to="UserApp.modeluser",
                verbose_name="User",
            ),
        ),
    ]
